### PR TITLE
update the barion pixel to the latest version, update the logo picture…

### PR DESCRIPTION
**Pull request by kevindree**
1. update the barion pixel to the latest version, since barion has changed his pixel code.
2. update the logo picture which will be shown in the checkout page, since the logo picture has been changed by barion.
3. change the icon link to barion homepage, since the previouse page is dispeared.

### CODE REVIEW

**Review by gcsecsey — APPROVED** [review]
Hi @kevindree, thanks for working on this PR! 🎉 

I've tested the changes, and everything seem to work as expected:
- Barion pixel code is added to the page source successfully
- Clicking on the logo redirects to the correct URL for both HU and EN locales
- New Barion logo on the checkout page looks good:
  CleanShot 2022-10-24 at 13 28 56@2x

**Comment by gcsecsey** [comment]
@szelpe could you please help with approving/merging this?

**Comment by szelpe** [comment]
Thanks, I released your changes to version 3.5

**Comment by kevindree** [comment]
I am very glad to contribute to this project, Thank you for all your effort as well,

**Pull request merged**
